### ISSUE TITLE
Custom Mappings Not Used for Optional Properties

### ISSUE THREAD

**Issue by pettyjamesm** [iheartradio/play-swagger#139]
Using swagger-custom-mappings.yml seems to fail when properties are Option[A] wrapped types.

Our application makes heavy use of case classes that wrap strings for type safety. eg:
```scala
final case class PostalCode(value: String)
object PostalCode {
  implicit val format: Format[PostalCode] = Format(Reads.of[String].map(PostalCode(_)), Writes[PostalCode](code => JsString(code.value)))
}
```

These values are overridden using the `scala-custom-mappings.yml` file, and work as expected when they're required values. However, when the values are inside of an `Option` wrapper, the overrides aren't used. For example, with:
```yaml
---
- type: api\.v1\.PostalCode
  specAsParameter:
    - type: string

- type: api\.v1\.Province
  specAsParameter:
    - type: string
```

I get the following result in the swagger.json

```json5
"api.v1.Address":{
  "properties": {
    "city":{"type":"string"},
    "province":{"type":"string"},  # Non-optional wrapper type, just like PostalCode. Works as expected.
    "postal":{"$ref":"#/definitions/api.v1.PostalCode"} # Optional, overridden type not used
  }
}
```
