### ISSUE TITLE
Custom mapping joda DateTime error

### ISSUE THREAD

**Issue by contact-mymoneytime** [iheartradio/play-swagger#140]
Default mapping of or.joda.time.DateTime is 
```
{
    type: "integer",
    format: "epoch"
}
```

Overriding this binding with swagger-custom-mappings.yml doesn't work. 
Here is the yml:
```  
- type: org\.joda\.time\.DateTime
  specAsParameter:
      - type: string
        format: date-time
```

**Comment by kbedel** [comment]
This is working for me, although I have a slightly different swagger-custom-mappings.yml file:

```
---
  - type: .*DateTime
    specAsParameter:
      - type: string
        format: date-time
```

This produces the following output fragment as expected:

```
"dueDate": {
"type": "string",
"format": "date-time"
}
```

**Comment by longliveenduro** [comment]
Can confirm org\.joda\.time\.DateTime does not work but  .*DateTime does

**Comment by alexander-myltsev** [comment]
Try this one:

```yml
---
- type: "org.joda.time.DateTime"
  specAsParameter:
    - type: string
      format: date-time
```
