### ISSUE TITLE
Support `Json.valueFormat`

### ISSUE THREAD

**Issue by lalnuo** [iheartradio/play-swagger#401]
If class is defined like this:

```scala
case class TaskId(value: UUID) extends AnyVal

object TaskId {
  implicit val jsonFormat = Json.valueFormat[TaskId]
}
```

And play is used for serialization:
```scala
Json.toJson(TaskId(UUID.randomUUID()))
```

It will serialize to:
```
"482a4c0a-dc04-4c67-8821-b93096978a3d"
```

It would be nice if play-swagger handled this automatically. Currently i'm writing mappings like this:

```
- type:models\.ids\.taskid
  specAsParameter:
    - type: string
      format: uuid
```

**Comment by vnt-83** [comment]
Hello. I'm writing (only one) mappings for UUID like this:

```
- type: uuid
  specAsParameter:
    - type: string
      format: uuid

```

in file conf/swagger-custom-mappings.yml
