### ISSUE TITLE
Swagger Custom Mappings not working with multiples parameters

### ISSUE THREAD

**Issue by samirbraga** [iheartradio/play-swagger#444]
I'm trying to document a simple Pagination object in `swagger-custom-mappings.yml` this way:

```yaml
- type: Pagination
  required: false
  specAsParameter:
    - type: integer
      name: pageSize
    - type: integer
      name: page
```
But, the rendered result is it:
![image](https://user-images.githubusercontent.com/15489754/153919239-8c7d3348-a21e-473f-a2c5-f54806b8a837.png)

Looking at the code, I found this block where only the first element of `specAsParameter` array is really interpreted correctly with type and etc. For example, in another object, I've used a list of filters as a query string parameter, but the type `array` can't be placed in another position than not first.

https://github.com/iheartradio/play-swagger/blob/526323d38ab87e6c5aa3dd7d94e9b1578ebc9bce/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L219-L236

Why this behavior?
