### ISSUE TITLE
Issue with java.util.Date and scala Map

### ISSUE THREAD

**Issue by sk3749614** [iheartradio/play-swagger#87]
I am having issues with case classes that contain Date and scala Map. These show up as entities which are then not able to be read by Swagger CodeGen. How do I handle these types? Below is the model that is being created

metaData (collection.immutable.map[string,string]),
createdAt (java.util.date),

**Comment by kailuowang** [comment]
playswagger doesn't support generating schema for map and java.util.date out of box. contribution to add those support is welcome, but in the meantime you can override those field with your own schema definition: this is one of the strengths of play-swagger, you can always override easily with your own swagger definition.

**Comment by yarosman** [comment]
You can create in `swagger-custom-mappings.yml` custom definiton for `map` type like this:
```
  - type: collection\.immutable\.map\[string\,string\]
    specAsParameter:
      - type: object
    specAsProperty:
      type: object
```
